InWhiteBoxBundle\Entity\CatalogItem:
    type: entity
    manyToOne:
        catalog:
            targetEntity: InWhiteBoxBundle\Entity\Catalog
            inversedBy: items
            joinColumn:
                name: catalog_id
                referencedColumnName: id
    table: null
    repositoryClass: InWhiteBoxBundle\Repository\CatalogItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        picture:
            type: string
            length: 255
        price:
            type: float
    lifecycleCallbacks: {  }
