<?php

namespace InWhiteBoxBundle\Repository;

/**
 * WebUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebUserRepository extends \Doctrine\ORM\EntityRepository
{
}
