in_white_box_homepage:
  path: /
  defaults: { _controller: InWhiteBoxBundle:Default:index }

# Админка
in_white_box_admin:
  path: /admin
  defaults: { _controller: "InWhiteBoxBundle:Admin:index" }
in_white_box_auth:
  path: /admin/auth
  defaults: {_controller: "InWhiteBoxBundle:Security:auth"}

# Каталог
catalog_index:
  path: /admin/catalog/
  defaults: { _controller: "InWhiteBoxBundle:Catalog:index" }
  methods: GET
catalog_show:
  path: /admin/catalog/{id}/show
  defaults: { _controller: "InWhiteBoxBundle:Catalog:show" }
  methods: GET
catalog_new:
  path: /admin/catalog/new
  defaults: { _controller: "InWhiteBoxBundle:Catalog:new" }
  methods: [GET, POST]
catalog_edit:
  path: /admin/catalog/{id}/edit
  defaults: { _controller: "InWhiteBoxBundle:Catalog:edit" }
  methods: [GET, POST]
catalog_delete:
  path: /admin/catalog/{id}/delete
  defaults: { _controller: "InWhiteBoxBundle:Catalog:delete" }
  methods: DELETE